### ISSUE TITLE
No performance governor!

### ISSUE THREAD

**Issue by JDC2389** [sirlucjan/workbench#1]
Please, pleaaaase include the performance governor for when people are gaming and need all cores to be maxed 100%. This cost me anywhere from 50-150fps in csgo. edit: actually my overclock is disabled as well for some reason I'm stuck on 3.5ghz max instead of my regular 4.5ghz. Is that because there isn't intel pstate enabled by default?

**Comment by sirlucjan** [comment]
I've enabled performance. You should enable:

```
### Set performance governor as default
_per_gov=
```
Works fine:

```
[lucjan@archlinux ~]$ zgrep -i PERFORMANCE /proc/config.gz
CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y
# Kernel Performance Events And Counters
# Performance monitoring
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
# CONFIG_PCIEASPM_PERFORMANCE is not set
CONFIG_DEVFREQ_GOV_PERFORMANCE=m
# Performance monitor support
```
```
[lucjan@archlinux ~]$ cpupower frequency-info
analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 800 MHz - 2.70 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 800 MHz and 2.70 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 1.69 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
```
```
CONFIG_MHASWELL=y
CONFIG_SMT_NICE=y
bfq [bfq-mq] none
Linux version 4.18.11.ll24-0.1-lucjan-git+ (lucjan@archlinux) (gcc version 8.2.1 20180831 (GCC)) #1 SMP PREEMPT Thu Sep 27 16:19:23 CEST 2018
Linux archlinux 4.18.11.ll24-0.1-lucjan-git+ #1 SMP PREEMPT Thu Sep 27 16:19:23 CEST 2018 x86_64 GNU/Linux
[    0.000000] pds: PDS-mq CPU Scheduler 0.99a by Alfred Chen.
[    0.062013] pds: cpu #0 affinity check mask - smt 0x00000004
[    0.062015] pds: cpu #0 affinity check mask - coregroup 0x0000000e
[    0.062016] pds: cpu #1 affinity check mask - smt 0x00000008
[    0.062016] pds: cpu #1 affinity check mask - coregroup 0x0000000d
[    0.062017] pds: cpu #2 affinity check mask - smt 0x00000001
[    0.062018] pds: cpu #2 affinity check mask - coregroup 0x0000000b
[    0.062019] pds: cpu #3 affinity check mask - smt 0x00000002
[    0.062020] pds: cpu #3 affinity check mask - coregroup 0x00000007
[    0.372407] io scheduler noop registered
[    0.372433] io scheduler bfq registered
[    0.372453] io scheduler bfq-sq registered (default)
[    0.372454] BFQ I/O-scheduler: v9 (with cgroups support)
[    0.372472] io scheduler bfq-mq registered
[    0.372473] BFQ I/O-scheduler: v9 (with cgroups support)
[    0.705436] UKSM: relative memcmp_cost = 184 hash=3902094187 cmp_ret=0.
```

**Comment by JDC2389** [comment]
Yes I've been digging a bit more, my bad, I was just peeved about building the linux-lqx aur package and not having my full clock speed. Building your linux-lucjan kernel now thanks. This is the output I got on the linux-lqx built from AUR. 

[carbon@carbon-pc ~]$ cpupower frequency-info
analyzing CPU 0:
  no or unknown cpufreq driver is active on this CPU
  CPUs which run at the same hardware frequency: Not Available
  CPUs which need to have their frequency coordinated by software: Not Available
  maximum transition latency:  Cannot determine or is not supported.
Not Available
  available cpufreq governors: Not Available
  Unable to determine current policy
  current CPU frequency: Unable to call hardware
  current CPU frequency:  Unable to call to kernel
  boost state support:
    Supported: yes
    Active: yes
I'm on an i5-4690k

I built your linux-lucjan-git kernel and it seems to be running gut, thanks.

**Comment by sirlucjan** [comment]
Please install inxi from AUR and:

```
inxi -xF | grep CPU
```

**Comment by JDC2389** [comment]
CPU:       Topology: Quad Core model: Intel Core i5-4690K bits: 64 type: MCP arch: Haswell

I'm on your linux-lucjan-git kernel atm and it seems to be running better than ever. I had issues with the compile from linux-lqx on AUR for some reason like I said unable to call hardware and kernel on that cpupower and it was stuck at 3.5ghz max.

**Comment by sirlucjan** [comment]
Paste:

```
cpupower frequency-info
```

**Comment by JDC2389** [comment]
[carbon@carbon-pc ~]$ cpupower frequency-info
analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 800 MHz - 4.50 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 800 MHz and 4.50 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 4.50 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes

**Comment by sirlucjan** [comment]
It seems to be ok

**Comment by JDC2389** [comment]
Yeah man as I was saying I switched kernels, the initial problem was with linux-lqx from AUR, I'm now on linux-lucjan-git, sorry for the confusion. This problem was on linux-lqx 4.18.10 from aur and it's updated now, might as well close the issue.

**Comment by sirlucjan** [comment]
You should edit PKGBUILD (linux-lqx) and add:

```
### Set performance governor as default
_per_gov=y
```

```
### Set performance governor
        if [ -n "$_per_gov" ]; then
                msg2 "Setting performance governor..."
                sed -i -e s'/^CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y/# CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL is not set/' \
                    -i -e s'/^# CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE is not set/CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y/' ./.config
                msg2 "Disabling uneeded governors..."
                sed -i -e s'/^CONFIG_CPU_FREQ_GOV_ONDEMAND=m/# CONFIG_CPU_FREQ_GOV_ONDEMAND is not set/' \
                    -i -e s'/^CONFIG_CPU_FREQ_GOV_CONSERVATIVE=m/# CONFIG_CPU_FREQ_GOV_CONSERVATIVE is not set/' \
                    -i -e s'/^CONFIG_CPU_FREQ_GOV_USERSPACE=m/# CONFIG_CPU_FREQ_GOV_USERSPACE is not set/' \
                    -i -e s'/^CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y/# CONFIG_CPU_FREQ_GOV_SCHEDUTIL is not set/' ./.config
        fi
```

**Comment by sirlucjan** [comment]
Let me know when you get a confirmation.

**Comment by JDC2389** [comment]
Yes, I got the performance governor working just fine.
